---
version: "3"
services:
  vector_sdk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vector.sdk
    volumes:
      - ./anki_vector:/root/.anki_vector/
      - ./code:/app/code
    restart: unless-stopped
